# Privacy Policy for AI Joke

Last Updated: February 4, 2026

AI Joke ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we handle information in the AI Joke mobile application.

## 1. Information Collection and Use

### On-Device Processing
AI Joke is designed with a "Privacy First" approach. All joke generation using Large Language Models (LLM) happens **locally on your device**. 
- **Keywords**: The words you input to generate jokes are processed in real-time on your device and are not transmitted to or stored on our servers.
- **Jokes**: The jokes generated by the AI are kept on your device unless you choose to share them.

### Data We Do Not Collect
- We do **not** collect personal identifiable information (PII) such as your name, email address, or phone number.
- We do **not** track your location.
- We do **not** record or store your generated jokes on any external servers.

## 2. Usage Tracking and Limits
To provide a fair experience for all users, AI Joke tracks the number of jokes generated per day to enforce daily limits. This tracking is done **locally on your device** using system storage. No usage data is linked to your identity.

## 3. In-App Purchases
If you choose to purchase a "Pro" version or reset your daily limits, the transaction is processed securely through Apple's App Store. We do not have access to your credit card information or billing details. Apple provides us with anonymized transaction receipts to validate your purchase.

## 4. Third-Party Services
AI Joke does not share any data with third-party advertisers or analytics providers. We do not sell your information.

## 5. Sharing
When you use the "Share" feature, the app generates an image of the joke. This image is only shared with the apps or people you explicitly choose through the system share sheet.

## 6. Your Rights
Since no personal data is collected or stored on our servers, there is no data for you to access or delete from us. You can manage your local app data by uninstalling the app.

## 7. Contact Us
If you have any questions about this Privacy Policy, please contact us at:
[https://james1895.xyz]

---
AI Joke is powered by Qwen3 model, operating under the Apache 2.0 license.
